RandomForest:
  model_type: RandomForest
  tuning_function: randomsearch
  tuning_function_params:
    n_iter: 5
    scoring: roc_auc 
    cv: 5
    verbose: 0
    n_jobs: -1
  hyperparameter_space:
    n_jobs: [-1]
    criterion: [mse]
    max_depth: [8, 12, 16, 32, 64]
    min_samples_leaf: [5, 10, 15, 20, 30, 40, 50]
    min_samples_split: [2, 5, 10, 15, 20]
    max_features: ['auto', 'sqrt', 'log2']
    n_estimators: [90, 120, 150, 300, 500, 800, 1000]

LightGBM:
  model_type: LightGBM
  tuning_function: randomsearch
  tuning_function_params:
    n_iter: 10
    scoring: roc_auc 
    cv: 4
    verbose: 0
    n_jobs: [-1]
  hyperparameter_space:
    n_jobs: [-1]
    is_unbalance: [True]
    max_depth: [5, 10, 11, 12, 13, 14, 15, 20]
    min_data_in_leaf: [5, 10, 15, 20, 25]
    num_leaves: [10, 20, 30, 50, 100, 300, 500]
    n_estimators: [100, 140, 150, 170, 200, 250, 300]

ExtraTrees:
  model_type: ExtraTrees
  tuning_function: randomsearch
  tuning_function_params:
    scoring: average_precision 
    cv: 4
    verbose: 0
    n_jobs: 2
  hyperparameter_space:
    max_depth: [8, 12,16, 32]
    min_samples_leaf: [20, 30, 40]
    min_samples_split: [20]
    n_estimators: [70, 90, 110]

XGBoost:
  model_type: XGBoost
  tuning_function: randomsearch
  tuning_function_params:
    scoring: average_precision 
    cv: 7
    verbose: -1
    n_jobs: -1
    n_iter: 25
  hyperparameter_space:
    boosting_type: ['gbdt', 'dart', 'rf']
    learning_rate: [0.1,0.01,0.001]
    n_estimators: [100,300,500]
    min_child_weight: [0, 5, 10, 30,100]
    scale_pos_weight: [12.25]
    gamma: [0, 0.5, 1,  2, 5,10,50,100]
    subsample: [0.4,0.6, 0.8, 1.0]
    colsample_bytree: [0.4,0.6, 0.8, 1.0]
    max_depth: [3, 4, 5,7,9,13,16]
    reg_alpha: [0.001, 0.01, 0.1,1,10,100]
    n_jobs: [-1]

CatBoost:
  model_type: CatBoost
  tuning_function: randomsearch
  tuning_function_params:
    n_iter: 1
    scoring: average_precision 
    cv: 2
    verbose: 0
    n_jobs: 1
  hyperparameter_space:
    learning_rate: [0.1, 0.01, 0.001]
    iterations: [100, 140, 150, 170, 200, 250, 300]